apiVersion: v1
kind: Pod
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: kafka-client
spec:
  volumes:
    - name: shared-vol
      persistentVolumeClaim:
        claimName: kafka-client-data
  containers:
  - name: kafka-client
    image: "wurstmeister/kafka:2.12-2.3.0"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
    volumeMounts:
      - name: shared-vol
        mountPath: /data
